language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "$(MATRIX_EVAL)"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
